package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConcernDegreeDic generated by hbm2java
 */
@Entity
@Table(name="concern_degree_dic"
    ,catalog="eme"
)
public class ConcernDegreeDic  implements java.io.Serializable {


     private Long id;
     private String concernDegree;
     private Set<Company> companies = new HashSet<Company>(0);

    public ConcernDegreeDic() {
    }

	
    public ConcernDegreeDic(String concernDegree) {
        this.concernDegree = concernDegree;
    }
    public ConcernDegreeDic(String concernDegree, Set<Company> companies) {
       this.concernDegree = concernDegree;
       this.companies = companies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="concern_degree", nullable=false, length=64)
    public String getConcernDegree() {
        return this.concernDegree;
    }
    
    public void setConcernDegree(String concernDegree) {
        this.concernDegree = concernDegree;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="concernDegreeDic")
    public Set<Company> getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set<Company> companies) {
        this.companies = companies;
    }




}


