package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetectStation generated by hbm2java
 */
@Entity
@Table(name="detect_station"
    ,catalog="eme"
)
public class DetectStation  implements java.io.Serializable {


     private Long id;
     private AdministrativeDivision administrativeDivision;
     private Epb epb;
     private String detectStationName;
     private Float lat;
     private Float lng;
     private Set<DataCollectionDevice> dataCollectionDevices = new HashSet<DataCollectionDevice>(0);
     private Set<Detect> detects = new HashSet<Detect>(0);
     private Set<DetectHistory> detectHistories = new HashSet<DetectHistory>(0);

    public DetectStation() {
    }

    public DetectStation(AdministrativeDivision administrativeDivision, Epb epb, String detectStationName, Float lat, Float lng, Set<DataCollectionDevice> dataCollectionDevices, Set<Detect> detects, Set<DetectHistory> detectHistories) {
       this.administrativeDivision = administrativeDivision;
       this.epb = epb;
       this.detectStationName = detectStationName;
       this.lat = lat;
       this.lng = lng;
       this.dataCollectionDevices = dataCollectionDevices;
       this.detects = detects;
       this.detectHistories = detectHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_divsion")
    public AdministrativeDivision getAdministrativeDivision() {
        return this.administrativeDivision;
    }
    
    public void setAdministrativeDivision(AdministrativeDivision administrativeDivision) {
        this.administrativeDivision = administrativeDivision;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_epb")
    public Epb getEpb() {
        return this.epb;
    }
    
    public void setEpb(Epb epb) {
        this.epb = epb;
    }
    
    @Column(name="detect_station_name", length=64)
    public String getDetectStationName() {
        return this.detectStationName;
    }
    
    public void setDetectStationName(String detectStationName) {
        this.detectStationName = detectStationName;
    }
    
    @Column(name="lat", precision=12, scale=0)
    public Float getLat() {
        return this.lat;
    }
    
    public void setLat(Float lat) {
        this.lat = lat;
    }
    
    @Column(name="lng", precision=12, scale=0)
    public Float getLng() {
        return this.lng;
    }
    
    public void setLng(Float lng) {
        this.lng = lng;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectStation")
    public Set<DataCollectionDevice> getDataCollectionDevices() {
        return this.dataCollectionDevices;
    }
    
    public void setDataCollectionDevices(Set<DataCollectionDevice> dataCollectionDevices) {
        this.dataCollectionDevices = dataCollectionDevices;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectStation")
    public Set<Detect> getDetects() {
        return this.detects;
    }
    
    public void setDetects(Set<Detect> detects) {
        this.detects = detects;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectStation")
    public Set<DetectHistory> getDetectHistories() {
        return this.detectHistories;
    }
    
    public void setDetectHistories(Set<DetectHistory> detectHistories) {
        this.detectHistories = detectHistories;
    }




}


