package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetectCategory generated by hbm2java
 */
@Entity
@Table(name="detect_category"
    ,catalog="eme"
)
public class DetectCategory  implements java.io.Serializable {


     private Long id;
     private String detectCategory;
     private Set<DetectFactor> detectFactors = new HashSet<DetectFactor>(0);

    public DetectCategory() {
    }

    public DetectCategory(String detectCategory, Set<DetectFactor> detectFactors) {
       this.detectCategory = detectCategory;
       this.detectFactors = detectFactors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="detect_category", length=20)
    public String getDetectCategory() {
        return this.detectCategory;
    }
    
    public void setDetectCategory(String detectCategory) {
        this.detectCategory = detectCategory;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detectCategory")
    public Set<DetectFactor> getDetectFactors() {
        return this.detectFactors;
    }
    
    public void setDetectFactors(Set<DetectFactor> detectFactors) {
        this.detectFactors = detectFactors;
    }




}


