package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmergencyResponsePlan generated by hbm2java
 */
@Entity
@Table(name="emergency_response_plan"
    ,catalog="eme"
)
public class EmergencyResponsePlan  implements java.io.Serializable {


     private Long id;
     private Company company;
     private EmergencyReponsePlanType emergencyReponsePlanType;
     private Epb epb;
     private String title;
     private Date creationDate;
     private String registCode;
     private String fileName;

    public EmergencyResponsePlan() {
    }

    public EmergencyResponsePlan(Company company, EmergencyReponsePlanType emergencyReponsePlanType, Epb epb, String title, Date creationDate, String registCode, String fileName) {
       this.company = company;
       this.emergencyReponsePlanType = emergencyReponsePlanType;
       this.epb = epb;
       this.title = title;
       this.creationDate = creationDate;
       this.registCode = registCode;
       this.fileName = fileName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_emergency_response_plan_type")
    public EmergencyReponsePlanType getEmergencyReponsePlanType() {
        return this.emergencyReponsePlanType;
    }
    
    public void setEmergencyReponsePlanType(EmergencyReponsePlanType emergencyReponsePlanType) {
        this.emergencyReponsePlanType = emergencyReponsePlanType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_epb")
    public Epb getEpb() {
        return this.epb;
    }
    
    public void setEpb(Epb epb) {
        this.epb = epb;
    }
    
    @Column(name="title", length=64)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    @Column(name="regist_code", length=64)
    public String getRegistCode() {
        return this.registCode;
    }
    
    public void setRegistCode(String registCode) {
        this.registCode = registCode;
    }
    
    @Column(name="file_name", length=64)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }




}


