package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IndustrySectorDic generated by hbm2java
 */
@Entity
@Table(name="industry_sector_dic"
    ,catalog="eme"
)
public class IndustrySectorDic  implements java.io.Serializable {


     private Long id;
     private String industrySector;
     private Set<Company> companies = new HashSet<Company>(0);

    public IndustrySectorDic() {
    }

	
    public IndustrySectorDic(String industrySector) {
        this.industrySector = industrySector;
    }
    public IndustrySectorDic(String industrySector, Set<Company> companies) {
       this.industrySector = industrySector;
       this.companies = companies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="industry_sector", nullable=false, length=64)
    public String getIndustrySector() {
        return this.industrySector;
    }
    
    public void setIndustrySector(String industrySector) {
        this.industrySector = industrySector;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="industrySectorDic")
    public Set<Company> getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set<Company> companies) {
        this.companies = companies;
    }




}


