package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IndustrialPark generated by hbm2java
 */
@Entity
@Table(name="industrial_park"
    ,catalog="eme"
)
public class IndustrialPark  implements java.io.Serializable {


     private Long id;
     private String industrialParkName;
     private Set<RiskBasicInfo> riskBasicInfos = new HashSet<RiskBasicInfo>(0);

    public IndustrialPark() {
    }

	
    public IndustrialPark(String industrialParkName) {
        this.industrialParkName = industrialParkName;
    }
    public IndustrialPark(String industrialParkName, Set<RiskBasicInfo> riskBasicInfos) {
       this.industrialParkName = industrialParkName;
       this.riskBasicInfos = riskBasicInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="industrial_park_name", nullable=false, length=64)
    public String getIndustrialParkName() {
        return this.industrialParkName;
    }
    
    public void setIndustrialParkName(String industrialParkName) {
        this.industrialParkName = industrialParkName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="industrialPark")
    public Set<RiskBasicInfo> getRiskBasicInfos() {
        return this.riskBasicInfos;
    }
    
    public void setRiskBasicInfos(Set<RiskBasicInfo> riskBasicInfos) {
        this.riskBasicInfos = riskBasicInfos;
    }




}


