package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WaterEnvId generated by hbm2java
 */
@Embeddable
public class WaterEnvId  implements java.io.Serializable {


     private String waterEnvName;
     private Float lat;
     private Float lng;
     private String emePerson;
     private String emeMobile;
     private Long idWaterEnvType;
     private Long idEnvFunc;

    public WaterEnvId() {
    }

    public WaterEnvId(String waterEnvName, Float lat, Float lng, String emePerson, String emeMobile, Long idWaterEnvType, Long idEnvFunc) {
       this.waterEnvName = waterEnvName;
       this.lat = lat;
       this.lng = lng;
       this.emePerson = emePerson;
       this.emeMobile = emeMobile;
       this.idWaterEnvType = idWaterEnvType;
       this.idEnvFunc = idEnvFunc;
    }
   

    @Column(name="water_env_name", length=64)
    public String getWaterEnvName() {
        return this.waterEnvName;
    }
    
    public void setWaterEnvName(String waterEnvName) {
        this.waterEnvName = waterEnvName;
    }

    @Column(name="lat", precision=12, scale=0)
    public Float getLat() {
        return this.lat;
    }
    
    public void setLat(Float lat) {
        this.lat = lat;
    }

    @Column(name="lng", precision=12, scale=0)
    public Float getLng() {
        return this.lng;
    }
    
    public void setLng(Float lng) {
        this.lng = lng;
    }

    @Column(name="eme_person", length=20)
    public String getEmePerson() {
        return this.emePerson;
    }
    
    public void setEmePerson(String emePerson) {
        this.emePerson = emePerson;
    }

    @Column(name="eme_mobile", length=20)
    public String getEmeMobile() {
        return this.emeMobile;
    }
    
    public void setEmeMobile(String emeMobile) {
        this.emeMobile = emeMobile;
    }

    @Column(name="id_water_env_type")
    public Long getIdWaterEnvType() {
        return this.idWaterEnvType;
    }
    
    public void setIdWaterEnvType(Long idWaterEnvType) {
        this.idWaterEnvType = idWaterEnvType;
    }

    @Column(name="id_env_func")
    public Long getIdEnvFunc() {
        return this.idEnvFunc;
    }
    
    public void setIdEnvFunc(Long idEnvFunc) {
        this.idEnvFunc = idEnvFunc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WaterEnvId) ) return false;
		 WaterEnvId castOther = ( WaterEnvId ) other; 
         
		 return ( (this.getWaterEnvName()==castOther.getWaterEnvName()) || ( this.getWaterEnvName()!=null && castOther.getWaterEnvName()!=null && this.getWaterEnvName().equals(castOther.getWaterEnvName()) ) )
 && ( (this.getLat()==castOther.getLat()) || ( this.getLat()!=null && castOther.getLat()!=null && this.getLat().equals(castOther.getLat()) ) )
 && ( (this.getLng()==castOther.getLng()) || ( this.getLng()!=null && castOther.getLng()!=null && this.getLng().equals(castOther.getLng()) ) )
 && ( (this.getEmePerson()==castOther.getEmePerson()) || ( this.getEmePerson()!=null && castOther.getEmePerson()!=null && this.getEmePerson().equals(castOther.getEmePerson()) ) )
 && ( (this.getEmeMobile()==castOther.getEmeMobile()) || ( this.getEmeMobile()!=null && castOther.getEmeMobile()!=null && this.getEmeMobile().equals(castOther.getEmeMobile()) ) )
 && ( (this.getIdWaterEnvType()==castOther.getIdWaterEnvType()) || ( this.getIdWaterEnvType()!=null && castOther.getIdWaterEnvType()!=null && this.getIdWaterEnvType().equals(castOther.getIdWaterEnvType()) ) )
 && ( (this.getIdEnvFunc()==castOther.getIdEnvFunc()) || ( this.getIdEnvFunc()!=null && castOther.getIdEnvFunc()!=null && this.getIdEnvFunc().equals(castOther.getIdEnvFunc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getWaterEnvName() == null ? 0 : this.getWaterEnvName().hashCode() );
         result = 37 * result + ( getLat() == null ? 0 : this.getLat().hashCode() );
         result = 37 * result + ( getLng() == null ? 0 : this.getLng().hashCode() );
         result = 37 * result + ( getEmePerson() == null ? 0 : this.getEmePerson().hashCode() );
         result = 37 * result + ( getEmeMobile() == null ? 0 : this.getEmeMobile().hashCode() );
         result = 37 * result + ( getIdWaterEnvType() == null ? 0 : this.getIdWaterEnvType().hashCode() );
         result = 37 * result + ( getIdEnvFunc() == null ? 0 : this.getIdEnvFunc().hashCode() );
         return result;
   }   


}


