package com.huihuan.eme.domain.db;
// Generated 2016-2-6 13:14:08 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Workmanship generated by hbm2java
 */
@Entity
@Table(name="workmanship"
    ,catalog="eme"
)
public class Workmanship  implements java.io.Serializable {


     private Long id;
     private Company company;
     private String title;
     private String description;
     private String fileName;

    public Workmanship() {
    }

	
    public Workmanship(Long id, String title) {
        this.id = id;
        this.title = title;
    }
    public Workmanship(Long id, Company company, String title, String description, String fileName) {
       this.id = id;
       this.company = company;
       this.title = title;
       this.description = description;
       this.fileName = fileName;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_company")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    
    @Column(name="title", nullable=false, length=64)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", length=1024)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="file_name", length=64)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }




}


